stages:
  - build
  - test

variables:
  BUILD_DIR: build

default:
  image: "kitware/cmake:3.29.5-gcc-12"

build:
  stage: build
  before_script:
    - apt-get update && apt-get install -y cmake ninja-build g++
  script:
    - cmake -S . -B $BUILD_DIR -G Ninja -DCMAKE_BUILD_TYPE=Release
    - cmake --build $BUILD_DIR
  artifacts:
    paths:
      - $BUILD_DIR

test:
  stage: test
  before_script:
    - apt-get update && apt-get install -y cmake ninja-build g++
  script:
    - cmake -S . -B $BUILD_DIR -G Ninja -DCMAKE_BUILD_TYPE=Release
    - cmake --build $BUILD_DIR
    - cd $BUILD_DIR
    - ctest --output-on-failure